title: Compute Blade
email: merocle@gmail.com
description: ''
baseurl: ''
url: ''
twitter_username: merocle
github_username: merocle
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed

# Color scheme supports "light" (default) and "dark"
color_scheme: light

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/Logo_black.png"
favicon_ico: "/assets/images/favicon.ico"

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

# Google Analytics Tracking (optional)
# Supports a CSV of tracking ID strings (eg. "UA-1234567-89,G-1AB234CDE5")
ga_tracking: G-LEDDFYXP5Z
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

# Footer content
# appears at the bottom of every page's main content
# Note: The footer_content option is deprecated and will be removed in a future major release. Please use `_includes/footer_custom.html` for more robustmarkup / liquid-based content.
footer_content: "Copyright &copy; 2023 Ivan Kuleshov."

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
#gh_edit_link: true # show or hide edit this page link
#gh_edit_link_text: "Edit this page on GitHub."
#gh_edit_repository: "https://github.com/just-the-docs/just-the-docs" # the github URL for your repo
#gh_edit_branch: "main" # the branch that your docs is served from
## gh_edit_source: docs # the source that your files originate from
#gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

nav_external_links:
  - title: Twitter
    url: https://twitter.com/Merocle
    hide_icon: false # set to true to hide the external link icon - defaults to false
  - title: Instagram
    url: https://www.instagram.com/uptime.lab/
    hide_icon: false # set to true to hide the external link icon - defaults to false
  - title: Discord community
    url: https://uplab.pro/discord/
    hide_icon: false # set to true to hide the external link icon - defaults to false

# Aux links for the upper right navigation
aux_links:
  "links tree":
    - "http://uplab.pro/ls"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# For copy button on code
enable_copy_code_button: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html


compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  # ignore:
  #   envs: all

plugins:
  - jekyll-redirect-from
